// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRplfrl5l61Uq1HxTK8CsLzXiy-TyfVjE',
    appId: '1:947500132553:web:02d267dc6ef102cc044518',
    messagingSenderId: '947500132553',
    projectId: 'chatmax-697f9',
    authDomain: 'chatmax-697f9.firebaseapp.com',
    storageBucket: 'chatmax-697f9.firebasestorage.app',
    measurementId: 'G-BYNH1HE4HW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApKZw4wRbEg225qqaIxt7bPKSFDADoL3k',
    appId: '1:947500132553:android:de9de29e75233399044518',
    messagingSenderId: '947500132553',
    projectId: 'chatmax-697f9',
    storageBucket: 'chatmax-697f9.firebasestorage.app',
  );

}